# Generated by Django 5.2.3 on 2026-06-11 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cocowa_consent_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when consent was last given or revoked', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cocowa_data_consent',
            field=models.BooleanField(default=False, help_text='User has consented to sharing their data with COCOWA'),
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of benefits allocated to this beneficiary', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='System.individualmember')),
            ],
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('child', 'Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('parent', 'Parent'), ('other', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aged_out', models.BooleanField(default=False, help_text='Set to True automatically when the dependant turns 18')),
                ('aged_out_date', models.DateField(blank=True, help_text='The date on which the dependant was auto-removed', null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='System.individualmember')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='System.individualmember')),
            ],
        ),
    ]
