# Generated by Django 5.2.3 on 2026-05-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_membership_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
