# Generated by Django 5.2.3 on 2026-05-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_remove_vehicle_membership_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='membership_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
