# Generated by Django 5.2.3 on 2026-05-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_vehicle_membership_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='membership_number',
        ),
    ]
