# Generated by Django 5.2.3 on 2026-05-29 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_partnerdonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnermember',
            name='donation_amount',
        ),
    ]
