# Generated by Django 5.2.3 on 2026-05-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_remove_partnermember_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('town_service', 'Town Service'), ('long_distance', 'Long Distance')], max_length=20),
        ),
    ]
