# Generated by Django 5.2.3 on 2026-06-01 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0008_event_alter_userprofile_role_complaint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('membership', 'Membership'), ('payment', 'Payment'), ('event', 'Event'), ('account', 'Account'), ('other', 'Other')], default='Membership', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReportCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('overloading', 'Overloading'), ('reckless_driving', 'Reckless Driving'), ('misconduct', 'Crew Misconduct'), ('fare_overcharge', 'Fare Overcharge'), ('harassment', 'Harassment'), ('unsafe_vehicle', 'Unsafe Vehicle'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('journey_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_incidents', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='System.saccomember')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='System.vehicle')),
            ],
        ),
    ]
