# Generated by Django 5.2.3 on 2026-06-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0009_complaint_category_complaint_ticket_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcases',
            name='number_plate',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcases',
            name='route',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reportcases',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('town_service', 'Town Service'), ('long_distance', 'Long Distance')], default='', max_length=20),
        ),
    ]
