# Generated by Django 5.2.3 on 2026-06-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0010_reportcases_number_plate_reportcases_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcases',
            name='sacco_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportcases',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='System.saccomember'),
        ),
        migrations.AlterField(
            model_name='reportcases',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='System.vehicle'),
        ),
    ]
