# Generated by Django 5.2.3 on 2026-06-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0011_reportcases_sacco_name_alter_reportcases_sacco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcases',
            old_name='sacco_name',
            new_name='external_sacco_name',
        ),
    ]
