from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('services/', views.services, name='services'),
    path('join/', views.join_membership, name='join'),
    path("payment/<str:member_type>/<int:member_id>/",views.payment_page, name="payment_page"),
    path('payment-status/<int:member_id>/', views.payment_status, name='payment_status'),
    path('membership/check/',views.check_membership,name='check_membership'),
    path("login/", views.custom_login, name="login"),
    path("dashboard/sacco/", views.sacco_dashboard, name="sacco_dashboard"),
    path("dashboard/individual/", views.individual_dashboard, name="individual_dashboard"),
    path("dashboard/partner/", views.partner_dashboard, name="partner_dashboard"),
    path("dashboard/manager/", views.manager_dashboard, name="manager_dashboard"),
    path("logout/", views.custom_logout, name="logout"),
    path("dashboard-redirect/", views.dashboard_redirect, name="dashboard_redirect"),
    path("partner/donation/", views.partner_donation, name="partner_donation"),
    path("partner/report/", views.partner_report, name="partner_report"),
    path('partner/report/pdf/', views.partner_report_pdf, name='partner_report_pdf'),
    path("complete-individual-profile/", views.complete_individual_profile, name="complete_individual_profile"),
    path('download-membership-card/', views.download_membership_card, name='download_membership_card'),
    path("complete-sacco-profile/", views.complete_sacco_profile, name="complete_sacco_profile"),
    path("complete-partner-profile/", views.complete_partner_profile, name="complete_partner_profile"),
    path('membership-card/', views.membership_card, name='membership_card'),
    path("tickets/new/", views.raise_complaint, name="raise_complaint"),
    path("tickets/", views.my_complaints, name="my_complaints"),
    path("report-cases/new/", views.report_cases, name="report_cases"),
    path("report-cases/", views.my_cases, name="my_cases"),
    path("manager/cases/", views.manager_cases, name="manager_cases"),
    path("manager/complaints/", views.manager_complaints, name="manager_complaints"),
    path("manager/complaints/update/<int:pk>/", views.update_complaint_status, name="update_complaint_status"),
    path("manager/report/", views.manager_report, name="manager_report"),
    path("manager/cases/update/", views.update_case_status, name="update_case_status"),
    path("members/individuals/", views.individuals_list, name="individuals_list"),
    path("members/saccos/", views.sacco_list, name="sacco_list"),
    path("members/partners/", views.partners_list, name="partners_list"),
    path("members/autocomplete/", views.member_autocomplete, name="member_autocomplete"),
    path("saccos/autocomplete/", views.sacco_autocomplete, name="sacco_autocomplete"),
    path("partners/autocomplete/", views.partner_autocomplete, name="partner_autocomplete"),  
    path("google-redirect/", views.google_redirect, name="google_redirect"), 
    path("select-role/", views.select_role, name="select_role"),
]